// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful"
import { Document } from "@contentful/rich-text-types"

export interface IBlogFields {
  /** title */
  title: string

  /** url */
  url: string

  /** summary */
  summary: string
}

export interface IBlog extends Entry<IBlogFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "blog"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IJobAssignmentFields {
  /** name */
  name: string

  /** activities */
  activities?: IJobEntry[] | undefined

  /** description */
  description: Document
}

export interface IJobAssignment extends Entry<IJobAssignmentFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "jobAssignment"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IJobEntryFields {
  /** title */
  title: string

  /** start date */
  startDate: string

  /** finish date */
  finishDate?: string | undefined

  /** body */
  body?: Document | undefined

  /** related works */
  relatedWorks?: IWork[] | undefined
}

export interface IJobEntry extends Entry<IJobEntryFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "jobEntry"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IJobPositionFields {
  /** name */
  name: string

  /** assignments */
  assignments?: IJobAssignment[] | undefined
}

export interface IJobPosition extends Entry<IJobPositionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "jobPosition"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IProfileFields {
  /** profileImage */
  profileImage: Asset
}

export interface IProfile extends Entry<IProfileFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "profile"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface ISiteFields {
  /** title */
  title: string

  /** facebookAppID */
  facebookAppId: string

  /** facebookAppPublisher */
  facebookAppPublisher: string

  /** twitterCardType */
  twitterCardType: string

  /** twitterCardOwner */
  twitterCardOwner: string

  /** description */
  description: string
}

export interface ISite extends Entry<ISiteFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "site"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface ISocialAccountFields {
  /** service */
  service: string

  /** url */
  url: string

  /** alternativeText */
  alternativeText: string

  /** color */
  color: string
}

export interface ISocialAccount extends Entry<ISocialAccountFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "socialAccount"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IWorkFields {
  /** name */
  name: string

  /** url */
  url: string

  /** performedAt */
  performedAt: { lat: number; lon: number }

  /** performedDate */
  performedDate: string

  /** eventURL */
  eventUrl?: string | undefined

  /** eventName */
  eventName: string
}

export interface IWork extends Entry<IWorkFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "work"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export type CONTENT_TYPE =
  | "blog"
  | "jobAssignment"
  | "jobEntry"
  | "jobPosition"
  | "profile"
  | "site"
  | "socialAccount"
  | "work"

export type LOCALE_CODE = "en-US" | "ja-JP"

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US"
