// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful"
import { Document } from "@contentful/rich-text-types"

export interface IWorkFields {
  /** name */
  name: string

  /** url */
  url: string

  /** performedAt */
  performedAt: { lat: number; lon: number }

  /** performedDate */
  performedDate: string

  /** eventURL */
  eventUrl: string

  /** eventName */
  eventName: string
}

export interface IWork extends Entry<IWorkFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "work"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

type CONTENT_TYPE = "work"

type LOCALE_CODE = "en-US"

type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US"
